export default ShakingCodes = {
    LOCATION_PERMISSION_ERROR: "LOCATION_PERMISSION_ERROR",
    LOCATION_DISABLED: "LOCATION_DISABLED",
    AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
    API_KEY_EXPIRED: "API_KEY_EXPIRED",
    TIMEOUT: "TIMEOUT",
    SERVER_ERROR: "SERVER_ERROR",
    SENSOR_ERROR: "SENSOR_ERROR"
  }